databases:
  - name: hanamimastery
    databaseName: hanamimastery
    user: hanamimastery

services:
  - type: web
    plan: free # optional (defaults to starter)
    name: Hanamimastery
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: HANAMI_ENV
        value: production
      - key: HANAMI_PORT
        value: 3000
      - key: PORT
        value: 3000

      - key: DATABASE_URL
        fromDatabase:
          name: hanamimastery
          property: connectionString
      # - key: RAILS_MASTER_KEY
      #   sync: false
